//
//  SymbolViewController.swift
//  TeXMath
//
//  Created by Jiaxin Shou on 2019/12/17.
//  Copyright © 2019 Jiaxin Shou. All rights reserved.
//

import Cocoa

class SymbolViewController: ViewControllerBase {
    override func viewDidLoad() {
        super.viewDidLoad()

        // MARK: Basic

        addSection(withName: "Basic")
        sections[0].addItem(withName: "Plus Minus", imageName: "PlusMinusButtonIcon", latexCode: "\\pm ")
        sections[0].addItem(withName: "Minus Plus", imageName: "MinusPlusButtonIcon", latexCode: "\\mp ")
        sections[0].addItem(withName: "Infinity", imageName: "InfinityButtonIcon", latexCode: "\\infty ")
        sections[0].addItem(withName: "Not Equal to", imageName: "NotEqualToButtonIcon", latexCode: "\\neq ")
        sections[0].addItem(withName: "Multiplication Sign", imageName: "MultiplicationSignButtonIcon", latexCode: "\\times ")
        sections[0].addItem(withName: "Division Sign", imageName: "DivisionSignButtonIcon", latexCode: "\\div ")
        sections[0].addItem(withName: "Proportional to", imageName: "ProportionalToButtonIcon", latexCode: "\\propto ")
        sections[0].addItem(withName: "Much Less Than", imageName: "MuchLessThanButtonIcon", latexCode: "\\ll ")
        sections[0].addItem(withName: "Much Greater Than", imageName: "MuchGreaterThanButtonIcon", latexCode: "\\gg ")
        sections[0].addItem(withName: "Less Than or Equal to", imageName: "LessThanOrEqualToButtonIcon", latexCode: "\\leq ")
        sections[0].addItem(withName: "Greater Than or Equal to", imageName: "GreaterThanOrEqualToButtonIcon", latexCode: "\\geq ")
        sections[0].addItem(withName: "Approximately Equal to", imageName: "ApproximatelyEqualToButtonIcon", latexCode: "\\cong ")
        sections[0].addItem(withName: "Asymptotic to", imageName: "AsymptoticToButtonIcon", latexCode: "\\approx ")
        sections[0].addItem(withName: "Identical to", imageName: "IdenticalToButtonIcon", latexCode: "\\equiv ")
        sections[0].addItem(withName: "For All", imageName: "ForAllButtonIcon", latexCode: "\\forall ")
        sections[0].addItem(withName: "There Exists", imageName: "ExistsButtonIcon", latexCode: "\\exists ")
        sections[0].addItem(withName: "There Does Not Exist", imageName: "NotExistsButtonIcon", latexCode: "\\nexists ")
        sections[0].addItem(withName: "Element of", imageName: "InButtonIcon", latexCode: "\\in ")
        sections[0].addItem(withName: "Contains as Member", imageName: "NiButtonIcon", latexCode: "\\ni ")
        sections[0].addItem(withName: "Not An Element of", imageName: "NotInButtonIcon", latexCode: "\\notin ")
        sections[0].addItem(withName: "Subset", imageName: "SubsetButtonIcon", latexCode: "\\subset ")
        sections[0].addItem(withName: "Subset or Equal", imageName: "SubsetEqualButtonIcon", latexCode: "\\subseteq ")
        sections[0].addItem(withName: "Superset", imageName: "SupersetButtonIcon", latexCode: "\\supset ")
        sections[0].addItem(withName: "Superset or Equal", imageName: "SupersetEqualButtonIcon", latexCode: "\\supseteq ")
        sections[0].addItem(withName: "Square Subset", imageName: "SqsubsetButtonIcon", latexCode: "\\sqsubset ")
        sections[0].addItem(withName: "Square Subset or Equal", imageName: "SqsubsetEqualButtonIcon", latexCode: "\\sqsubseteq ")
        sections[0].addItem(withName: "Square Superset", imageName: "SqsupersetButtonIcon", latexCode: "\\sqsupset ")
        sections[0].addItem(withName: "Square Superset or Equal", imageName: "SqsupersetEqualButtonIcon", latexCode: "\\sqsupseteq ")
        sections[0].addItem(withName: "Partial Differential", imageName: "PartialDifferentialButtonIcon", latexCode: "\\partial ")
        sections[0].addItem(withName: "Angle", imageName: "AngleButtonIcon", latexCode: "\\angle ")
        sections[0].addItem(withName: "Intersection", imageName: "CapButtonIcon", latexCode: "\\cap ")
        sections[0].addItem(withName: "Union", imageName: "CupButtonIcon", latexCode: "\\cup ")
        sections[0].addItem(withName: "Multiset Union", imageName: "UplusButtonIcon", latexCode: "\\uplus ")
        sections[0].addItem(withName: "Square Cap", imageName: "SqcapButtonIcon", latexCode: "\\sqcap ")
        sections[0].addItem(withName: "Square Cup", imageName: "SqcupButtonIcon", latexCode: "\\sqcup ")
        sections[0].addItem(withName: "Logical And", imageName: "WedgeButtonIcon", latexCode: "\\wedge ")
        sections[0].addItem(withName: "Logical Or", imageName: "VeeButtonIcon", latexCode: "\\vee ")
        sections[0].addItem(withName: "Circled Dot", imageName: "CircledDotButtonIcon", latexCode: "\\odot ")
        sections[0].addItem(withName: "Circled Minus", imageName: "CircledMinusButtonIcon", latexCode: "\\ominus ")
        sections[0].addItem(withName: "Circled Plus", imageName: "CircledPlusButtonIcon", latexCode: "\\oplus ")
        sections[0].addItem(withName: "Circled Slash", imageName: "CircledSlashButtonIcon", latexCode: "\\oslash ")
        sections[0].addItem(withName: "Circled Times", imageName: "CircledTimesButtonIcon", latexCode: "\\otimes ")
        sections[0].addItem(withName: "Left Arrow", imageName: "LeftArrowButtonIcon", latexCode: "\\leftarrow ")
        sections[0].addItem(withName: "Right Arrow", imageName: "RightArrowButtonIcon", latexCode: "\\rightarrow ")
        sections[0].addItem(withName: "Up Arrow", imageName: "UpArrowButtonIcon", latexCode: "\\uparrow ")
        sections[0].addItem(withName: "Down Arrow", imageName: "DownArrowButtonIcon", latexCode: "\\downarrow ")
        sections[0].addItem(withName: "Left Double Arrow", imageName: "LeftDoubleArrowButtonIcon", latexCode: "\\Leftarrow ")
        sections[0].addItem(withName: "Right Double Arrow", imageName: "RightDoubleArrowButtonIcon", latexCode: "\\Rightarrow ")
        sections[0].addItem(withName: "Left-Right Arrow", imageName: "LeftRightArrowButtonIcon", latexCode: "\\leftrightarrow ")
        sections[0].addItem(withName: "Left-Right Double Arrow", imageName: "LeftRightDoubleArrowButtonIcon", latexCode: "\\Leftrightarrow ")
        sections[0].addItem(withName: "Therefore", imageName: "ThereforeButtonIcon", latexCode: "\\therefore ")
        sections[0].addItem(withName: "Because", imageName: "BecauseButtonIcon", latexCode: "\\because ")
        sections[0].addItem(withName: "Dot Operator", imageName: "CdotButtonIcon", latexCode: "\\cdot ")
        sections[0].addItem(withName: "Midline Horizontal Ellipsis", imageName: "CdotsButtonIcon", latexCode: "\\cdots ")
        sections[0].addItem(withName: "Vertical Ellipsis", imageName: "VdotsButtonIcon", latexCode: "\\vdots ")
        sections[0].addItem(withName: "Diagonal Ellipsis", imageName: "DdotsButtonIcon", latexCode: "\\ddots ")

        // MARK: Lowercase

        addSection(withName: "Lowercase")
        sections[1].addItem(withName: "Alpha", imageName: "LowercaseAlphaButtonIcon", latexCode: "\\alpha ")
        sections[1].addItem(withName: "Beta", imageName: "LowercaseBetaButtonIcon", latexCode: "\\beta ")
        sections[1].addItem(withName: "Gamma", imageName: "LowercaseGammaButtonIcon", latexCode: "\\gamma ")
        sections[1].addItem(withName: "Delta", imageName: "LowercaseDeltaButtonIcon", latexCode: "\\delta ")
        sections[1].addItem(withName: "Epsilon Variant", imageName: "LowercaseVarepsilonButtonIcon", latexCode: "\\varepsilon ")
        sections[1].addItem(withName: "Epsilon", imageName: "LowercaseEpsilonButtonIcon", latexCode: "\\epsilon ")
        sections[1].addItem(withName: "Zeta", imageName: "LowercaseZetaButtonIcon", latexCode: "\\zeta ")
        sections[1].addItem(withName: "Eta", imageName: "LowercaseEtaButtonIcon", latexCode: "\\eta ")
        sections[1].addItem(withName: "Theta", imageName: "LowercaseThetaButtonIcon", latexCode: "\\theta ")
        sections[1].addItem(withName: "Theta Variant", imageName: "LowercaseVarthetaButtonIcon", latexCode: "\\vartheta ")
        sections[1].addItem(withName: "Iota", imageName: "LowercaseIotaButtonIcon", latexCode: "\\iota ")
        sections[1].addItem(withName: "Kappa", imageName: "LowercaseKappaButtonIcon", latexCode: "\\kappa ")
        sections[1].addItem(withName: "Kappa Variant", imageName: "LowercaseVarkappaButtonIcon", latexCode: "\\varkappa ")
        sections[1].addItem(withName: "Lambda", imageName: "LowercaseLambdaButtonIcon", latexCode: "\\lambda ")
        sections[1].addItem(withName: "Mu", imageName: "LowercaseMuButtonIcon", latexCode: "\\mu ")
        sections[1].addItem(withName: "Nu", imageName: "LowercaseNuButtonIcon", latexCode: "\\nu ")
        sections[1].addItem(withName: "Xi", imageName: "LowercaseXiButtonIcon", latexCode: "\\xi ")
        sections[1].addItem(withName: "Omicron", imageName: "LowercaseOmicronButtonIcon", latexCode: "o ")
        sections[1].addItem(withName: "Pi", imageName: "LowercasePiButtonIcon", latexCode: "\\pi ")
        sections[1].addItem(withName: "Pi Variant", imageName: "LowercaseVarpiButtonIcon", latexCode: "\\varpi ")
        sections[1].addItem(withName: "Rho", imageName: "LowercaseRhoButtonIcon", latexCode: "\\rho ")
        sections[1].addItem(withName: "Rho Variant", imageName: "LowercaseVarrhoButtonIcon", latexCode: "\\varrho ")
        sections[1].addItem(withName: "Sigma", imageName: "LowercaseSigmaButtonIcon", latexCode: "\\sigma ")
        sections[1].addItem(withName: "Sigma Variant", imageName: "LowercaseVarsigmaButtonIcon", latexCode: "\\varsigma ")
        sections[1].addItem(withName: "Tau", imageName: "LowercaseTauButtonIcon", latexCode: "\\tau ")
        sections[1].addItem(withName: "Upsilon", imageName: "LowercaseUpsilonButtonIcon", latexCode: "\\upsilon ")
        sections[1].addItem(withName: "Phi Variant", imageName: "LowercaseVarphiButtonIcon", latexCode: "\\varphi ")
        sections[1].addItem(withName: "Phi", imageName: "LowercasePhiButtonIcon", latexCode: "\\phi ")
        sections[1].addItem(withName: "Chi", imageName: "LowercaseChiButtonIcon", latexCode: "\\chi ")
        sections[1].addItem(withName: "Psi", imageName: "LowercasePsiButtonIcon", latexCode: "\\psi ")
        sections[1].addItem(withName: "Omega", imageName: "LowercaseOmegaButtonIcon", latexCode: "\\omega ")

        // MARK: Uppercase

        addSection(withName: "Uppercase")
        sections[2].addItem(withName: "Delta", imageName: "UppercaseDeltaButtonIcon", latexCode: "\\Delta ")
        sections[2].addItem(withName: "Gamma", imageName: "UppercaseGammaButtonIcon", latexCode: "\\Gamma ")
        sections[2].addItem(withName: "Lambda", imageName: "UppercaseLambdaButtonIcon", latexCode: "\\Lambda ")
        sections[2].addItem(withName: "Omega", imageName: "UppercaseOmegaButtonIcon", latexCode: "\\Omega ")
        sections[2].addItem(withName: "Phi", imageName: "UppercasePhiButtonIcon", latexCode: "\\Phi ")
        sections[2].addItem(withName: "Pi", imageName: "UppercasePiButtonIcon", latexCode: "\\Pi ")
        sections[2].addItem(withName: "Psi", imageName: "UppercasePsiButtonIcon", latexCode: "\\Psi ")
        sections[2].addItem(withName: "Sigma", imageName: "UppercaseSigmaButtonIcon", latexCode: "\\Sigma ")
        sections[2].addItem(withName: "Theta", imageName: "UppercaseThetaButtonIcon", latexCode: "\\Theta ")
        sections[2].addItem(withName: "Upsilon", imageName: "UppercaseUpsilonButtonIcon", latexCode: "\\Upsilon ")
        sections[2].addItem(withName: "Xi", imageName: "UppercaseXiButtonIcon", latexCode: "\\Xi ")

        // MARK: Letter-Like

        addSection(withName: "Letter-Like Symbols")
        sections[3].addItem(withName: "Digamma", imageName: "DigammaButtonIcon", latexCode: "\\digamma ")
        sections[3].addItem(withName: "Script Small L", imageName: "EllButtonIcon", latexCode: "\\ell ")
        sections[3].addItem(withName: "Weierstrass Elliptic Function", imageName: "WpButtonIcon", latexCode: "\\wp ")
        sections[3].addItem(withName: "Real Part", imageName: "ReButtonIcon", latexCode: "\\Re ")
        sections[3].addItem(withName: "Aleph", imageName: "AlephButtonIcon", latexCode: "\\aleph ")
        sections[3].addItem(withName: "Beth", imageName: "BethButtonIcon", latexCode: "\\beth ")
        sections[3].addItem(withName: "Daleth", imageName: "DalethButtonIcon", latexCode: "\\daleth ")
        sections[3].addItem(withName: "Gimel", imageName: "GimelButtonIcon", latexCode: "\\gimel ")
    }
}
